export const capitalMapping = ['O','100-250k','250-500k' ,'500k-1M' ,'1M-5M' ,'5M+']

export const tablePage = [
  {
    id: 1,
    dateReceived: "5/21/17",
    familymembers: "Irene",
    dealname: "Freedom deal",
    investmenttype: "TV Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    quill:
      "<p><u>Four</u> score and <strong>seven</strong> years ago. Our fathers said<em> </em><em style='background-color: rgb(255, 153, 0);'>something</em>.</p><p>newline hello</p>",
    keypeople: "Ernie and Fred",
    background: "",
    leadPerson: ""
  },
  {
    id: 2,
    dateReceived: "5/22/17",
    familymembers: "Irene/MS/Karen",
    dealname: "Tim Avery film project",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 2,
    status: "Done",
    keypeople: "Ernie",
    background: "",
    leadPerson: ""
  },
  {
    id: 3,
    dateReceived: "5/23/17",
    familymembers: "Tammy/Bart/Adam",
    dealname: "ET entertainment",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 3,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 4,
    dateReceived: "5/24/17",
    familymembers: "Irene",
    dealname: "One Year Tour",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 4,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 5,
    dateReceived: "5/25/17",
    familymembers: "Irene",
    dealname: "Eta Hope Tour",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 5,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 6,
    dateReceived: "5/26/17",
    familymembers: "Irene",
    dealname: "Sand's Visit",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 7,
    dateReceived: "5/27/17",
    familymembers: "Irene",
    dealname: "Film festival",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 8,
    dateReceived: "5/21/17",
    familymembers: "Irene",
    dealname: "Freedom deal",
    investmenttype: "TV Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    quill:
      "<p><u>Four</u> score and <strong>seven</strong> years ago. Our fathers said<em> something</em>.</p> newline hello",
    keypeople: "",
    background: "",
    leadPerson: ""
  },

  {
    id: 9,
    dateReceived: "5/22/17",
    familymembers: "Irene/MS/Karen",
    dealname: "Help Tim Avery",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 10,
    dateReceived: "5/23/17",
    familymembers: "Tammy/Bart/Adam",
    dealname: "ET entertainment",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 11,
    dateReceived: "5/21/17",
    familymembers: "Irene",
    dealname: "Freedom deal",
    investmenttype: "TV Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    quill:
      "<p><u>Four</u> score and <strong>seven</strong> years ago. Our fathers said<em> something</em>.</p> newline hello",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 12,
    dateReceived: "5/22/17",
    familymembers: "Irene/MS/Karen",
    dealname: "Tim Avery film project",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 13,
    dateReceived: "5/23/17",
    familymembers: "Tammy/Bart/Adam",
    dealname: "ET entertainment",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 14,
    dateReceived: "5/21/17",
    familymembers: "Irene",
    dealname: "Freedom deal",
    investmenttype: "TV Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    quill:
      "<p><u>Four</u> score and <strong>seven</strong> years ago. Our fathers said<em> something</em>.</p> newline hello",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 15,
    dateReceived: "5/22/17",
    familymembers: "Irene/MS/Karen",
    dealname: "Tim Avery film project",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 16,
    dateReceived: "5/23/17",
    familymembers: "Tammy/Bart/Adam",
    dealname: "ET entertainment",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 17,
    dateReceived: "5/21/17",
    familymembers: "Irene",
    dealname: "Freedom deal",
    investmenttype: "TV Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    quill:
      "<p><u>Four</u> score and <strong>seven</strong> years ago. Our fathers said<em> something</em>.</p> newline hello",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 18,
    dateReceived: "5/22/17",
    familymembers: "Irene/MS/Karen",
    dealname: "Tim Avery film project",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 19,
    dateReceived: "5/23/17",
    familymembers: "Tammy/Bart/Adam",
    dealname: "ET entertainment",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 20,
    dateReceived: "5/21/17",
    familymembers: "Irene",
    dealname: "Freedom deal",
    investmenttype: "TV Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    quill:
      "<p><u>Four</u> score and <strong>seven</strong> years ago. Our fathers said<em> something</em>.</p> newline hello",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 21,
    dateReceived: "5/22/17",
    familymembers: "Irene/MS/Karen",
    dealname: "Tim Avery film project",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 22,
    dateReceived: "5/23/17",
    familymembers: "Tammy/Bart/Adam",
    dealname: "ET entertainment",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 23,
    dateReceived: "5/21/17",
    familymembers: "Irene",
    dealname: "Freedom deal",
    investmenttype: "TV Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    quill:
      "<p><u>Four</u> score and <strong>seven</strong> years ago. Our fathers said<em> something</em>.</p> newline hello",

    keypeople: "",
    background: "",
    leadPerson: ""
  },

  {
    id: 24,
    dateReceived: "5/22/17",
    familymembers: "Irene/MS/Karen",
    dealname: "Tim Avery film project",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  },
  {
    id: 25,
    dateReceived: "5/23/17",
    familymembers: "Tammy/Bart/Adam",
    dealname: "ET entertainment",
    investmenttype: "Entertainment",
    financials: "Yes",
    legalreview: "Yes",
    reqcapital: 1,
    status: "Done",
    keypeople: "",
    background: "",
    leadPerson: ""
  }
];
/*
  const columns = [
    { key: "received", name: "Date received" },
    { key: "familymembers", name: "Family members" },
    { key: "dealname", name: "Deal name" },
    { key: "investmenttype", name: "Investment type" },
    { key: "keypeople", name: "Key people" },
    { key: "financials", name: "Fiancials" },
    { key: "legalreview", name: "Legal review" },
    { key: "background", name: "Background" },
    { key: "reqcapital", name: "Req capital" },
    { key: "recommend", name: "Recommend" },
    { key: "status", name: "Status" },
    { key: "leadperson", name: "Lead person" }
  ];
*/
